importScripts(
  "background/constants.js",
  "fast-commands.js",
  "background/pending-plans.js",
  "background/content-messaging.js",
  "background/cdp-core.js",
  "background/axtree.js",
  "background/cdp-exec.js",
  "background/debug-recording.js",
  "background/api-config.js",
  "background/execution.js",
  "background/navigation.js",
  "background/sidepanel.js",
  "background/messages.js",
  "background/events.js"
);
